name: Check

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - ready_for_review
      - reopened

jobs:
  check_ci:
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.pull_request.labels.*.name, 'run-ci')}}
    steps:
      - run: |
            echo "::warning file=.github/workflows/pr-check.yml,line=1,col=1,endColumn=1::Please request reviews"
            exit 101
  lint:
    name: Lint
    if: contains(github.event.pull_request.labels.*.name, 'run-ci')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 20
      - uses: actions/setup-node@main
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: corepack enable
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run lint
      - run: pnpm run commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
