import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import './globals.css'

export const metadata: Metadata = {
  title: '/* @echo name */',
  description: 'Generated by create next app',
  icons: 'https://avatars.githubusercontent.com/u/41888457?s=200&v=4',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
