name: Release Docker image for the app

on:
  release:
    types: [published]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get APP_VSN
      id: get-app-vsn
      run: echo "APP_VSN=$(awk -F '"' '/"version"/ { print $4 }' package.json)" >> $GITHUB_OUTPUT

    - name: Get APP_NAME
      run: echo "APP_NAME=$(awk -F '"' '/"name"/ { print $4 }' package.json)" >> $GITHUB_OUTPUT
      id: get-app-name

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./deploy/Dockerfile
        build-args: |
          APP_VSN=${{ steps.get-app-vsn.outputs.APP_VSN }}
          APP_NAME=${{ steps.get-app-name.outputs.APP_NAME }}
        push: true
        tags: |
          ghcr.io/byzanteam/${{ steps.get-app-name.outputs.APP_NAME }}:${{ steps.get-app-vsn.outputs.APP_VSN }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
