name: Release Docker image for the app

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: image-builder
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Build and push
      uses: byzanteam/jet-actions/fe-build-image@main
      with:
        registries: |-
          ${{ secrets.ALIYUN_JET_REGISTRY }}
          ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
        cache_type: registry
